<%@ page title="" language="VB" masterpagefile="~/MasterPage.master" autoeventwireup="false" inherits="Default2, App_Web_l55bdqje" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style2 {
            width: 100%;
        }
        .auto-style3 {
            width: 31px;
        }
        .auto-style4 {
            width: 33px;
        }
        .auto-style5 {
            text-align: right;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table class="auto-style2">
        <tr>
            <td class="auto-style3">
                &nbsp;</td>
            <td>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:BD_NEGOCIOSREPConnectionString %>" 
                    SelectCommand="select * from sg_autorizaciones where usuario=@usuario"
                    deletecommand="delete from sg_autorizaciones where id_autorizacion=@id_autorizacion"
                    updatecommand="update sg_autorizaciones set
                                     id_asesor=@id_asesor
                                    ,id_establecimiento=@id_establecimiento
                                    ,region=@region
                                    ,gerencia_general=@gerencia_general
                                    ,negocios=@negocios
                                    ,planeamiento_comercial=@planeamiento_comercial
                                    ,planeamiento_control_gestion=@planeamiento_control_gestion
                                    ,talento_humano=@talento_humano
                                    ,admin=@admin
                                    where id_autorizacion=@id_autorizacion"
                    >
                    <SelectParameters>
                        <asp:ControlParameter ControlID="TextBox1" Name="usuario" PropertyName="Text" />
                    </SelectParameters>
                </asp:SqlDataSource>
            </td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td class="auto-style4">&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style3">&nbsp;</td>
            <td>Usuario:</td>
            <td>
                <asp:TextBox ID="TextBox1" runat="server" Width="438px"></asp:TextBox>
            </td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td class="auto-style5">
                <asp:Button ID="Button1" runat="server" Text="Buscar" Width="88px" />
            </td>
            <td class="auto-style4">&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style3">&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td class="auto-style5">
                <asp:Button ID="Button2" runat="server" Text="Insertar" Width="88px" PostBackUrl="~/Configuracion.aspx" />
            </td>
            <td class="auto-style4">&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style3">&nbsp;</td>
            <td colspan="8" rowspan="6">
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id_autorizacion" DataSourceID="SqlDataSource1" CellPadding="4" ForeColor="#333333" GridLines="None">
                    <AlternatingRowStyle BackColor="White" />
                    <Columns>
                        <asp:BoundField DataField="id_autorizacion" HeaderText="id_autorizacion" InsertVisible="False" ReadOnly="True" SortExpression="id_autorizacion" Visible="False" />
                        <asp:BoundField DataField="usuario" HeaderText="Usuario" SortExpression="usuario" />
                        <asp:TemplateField HeaderText="Región" SortExpression="region">
                            <EditItemTemplate>
                                <asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="SqlDataSource2" DataTextField="region" DataValueField="region" Height="18px" Width="180px" SelectedValue='<%# Bind("region") %>'>
                                </asp:DropDownList>
                                <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:BD_NEGOCIOSREPConnectionString %>" SelectCommand="select region=null
union all
Select distinct region from ge_establecimientos"></asp:SqlDataSource>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("region") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Establecimiento" SortExpression="id_establecimiento">
                            <EditItemTemplate>
                                <asp:DropDownList ID="DropDownList2" runat="server" DataSourceID="SqlDataSource3" DataTextField="establecimiento" DataValueField="id_establecimiento" SelectedValue='<%# Bind("id_establecimiento") %>' Width="193px">
                                </asp:DropDownList>
                                <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:BD_NEGOCIOSREPConnectionString %>" SelectCommand="select id_establecimiento=NULL, establecimiento=NULL
union all
select id_establecimiento, establecimiento
from ge_establecimientos
where id_establecimiento&lt;&gt;1"></asp:SqlDataSource>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label2" runat="server" Text='<%# Bind("id_establecimiento") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Asesor" SortExpression="id_asesor">
                            <EditItemTemplate>
                                <asp:DropDownList ID="DropDownList3" runat="server" DataSourceID="SqlDataSource4" DataTextField="asesor" DataValueField="id_asesor" SelectedValue='<%# Bind("id_asesor") %>' Width="231px">
                                </asp:DropDownList>
                                <asp:SqlDataSource ID="SqlDataSource4" runat="server" ConnectionString="<%$ ConnectionStrings:BD_NEGOCIOSREPConnectionString %>" SelectCommand="select id_asesor=null,asesor=null
union all
select id_asesor,asesor
from ge_asesores
where id_asesor&lt;&gt;1 and asesor is not null
order by 2"></asp:SqlDataSource>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label3" runat="server" Text='<%# Bind("id_asesor") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:CheckBoxField DataField="gerencia_general" HeaderText="gerencia_general" SortExpression="gerencia_general" />
                        <asp:CheckBoxField DataField="negocios" HeaderText="negocios" SortExpression="negocios" />
                        <asp:CheckBoxField DataField="planeamiento_comercial" HeaderText="planeamiento_comercial" SortExpression="planeamiento_comercial" />
                        <asp:CheckBoxField DataField="planeamiento_control_gestion" HeaderText="planeamiento_control_gestion" SortExpression="planeamiento_control_gestion" />
                        <asp:CheckBoxField DataField="talento_humano" HeaderText="talento_humano" SortExpression="talento_humano" />
                        <asp:CheckBoxField DataField="admin" HeaderText="admin" SortExpression="admin" />
                    </Columns>
                    <EditRowStyle BackColor="#2461BF" />
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EFF3FB" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#F5F7FB" />
                    <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                    <SortedDescendingCellStyle BackColor="#E9EBEF" />
                    <SortedDescendingHeaderStyle BackColor="#4870BE" />
                </asp:GridView>
            </td>
            <td class="auto-style4">&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style3">&nbsp;</td>
            <td class="auto-style4">&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style3">&nbsp;</td>
            <td class="auto-style4">&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style3">&nbsp;</td>
            <td class="auto-style4">&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style3">&nbsp;</td>
            <td class="auto-style4">&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style3">&nbsp;</td>
            <td class="auto-style4">&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style3">&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td class="auto-style4">&nbsp;</td>
        </tr>
    </table>
</asp:Content>

